### PR TITLE
Tests for opentelemetry - gRPC, Temporal

### PR DESCRIPTION
**Pull request by cv65kr**
# Reason for This PR

Tests for:
- https://github.com/roadrunner-server/otel/pull/40
- https://github.com/roadrunner-server/otel/pull/41
- https://github.com/temporalio/roadrunner-temporal/pull/322
- https://github.com/roadrunner-server/grpc/pull/69

## Description of Changes

Testing cases

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the MIT license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

**Comment by rustatian** [comment]
Hey @cv65kr 👋🏻 

Have you tested that locally?

**Comment by rustatian** [comment]
BTW, you may install `golangci-lint` locally and check the code before committing the changes (optional for sure).
Here is the tutorial: https://golangci-lint.run/usage/install/
And after installation just execute: `golangci-lint --build-tags=race run`

**Comment by cv65kr** [comment]
@rustatian yes, all tested. Ok will install this linter and push one more commit.

And yes unfortunately because of releases I used "replace".

**Comment by rustatian** [comment]
> Ok will install this linter and push one more commit.

Yeah, you may save a few minutes waiting for the CI results on the GitHub actions side 😃

**Comment by cv65kr** [comment]
Looks like yaml files was not pushed somehow 🤔

**Comment by cv65kr** [comment]
@rustatian PR updated, looks like some tests failed but there are not related with my changes.

**Comment by rustatian** [comment]
@cv65kr Ok, all PRs are merged and tagged ⚡

**Comment by cv65kr** [comment]
@rustatian updated 😄

**Comment by rustatian** [comment]
@cv65kr One note, you have to use the `stderr` collector for the `otel` plugin and capture the output, not from the `stdout`. This is done, because the `>= Go 1.19.5` captures the coverage from the `stdout`, but we're closing it in the tests. You may look at the `plugins/http/otel` tests which I recently updated.

**Comment by cv65kr** [comment]
@rustatian alright, done

**Review by rustatian — APPROVED** [review]

**Pull request merged**
